// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: poc.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PocScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls string `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
}

func (x *PocScanReq) Reset() {
	*x = PocScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PocScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PocScanReq) ProtoMessage() {}

func (x *PocScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_poc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PocScanReq.ProtoReflect.Descriptor instead.
func (*PocScanReq) Descriptor() ([]byte, []int) {
	return file_poc_proto_rawDescGZIP(), []int{0}
}

func (x *PocScanReq) GetUrls() string {
	if x != nil {
		return x.Urls
	}
	return ""
}

type PocScanResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonResults string `protobuf:"bytes,1,opt,name=jsonResults,proto3" json:"jsonResults,omitempty"`
}

func (x *PocScanResult) Reset() {
	*x = PocScanResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PocScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PocScanResult) ProtoMessage() {}

func (x *PocScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_poc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PocScanResult.ProtoReflect.Descriptor instead.
func (*PocScanResult) Descriptor() ([]byte, []int) {
	return file_poc_proto_rawDescGZIP(), []int{1}
}

func (x *PocScanResult) GetJsonResults() string {
	if x != nil {
		return x.JsonResults
	}
	return ""
}

var File_poc_proto protoreflect.FileDescriptor

var file_poc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x70, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x6f, 0x63, 0x53, 0x63, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x31, 0x0a, 0x0d, 0x50, 0x6f, 0x63, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0x4d, 0x0a, 0x11, 0x52,
	0x75, 0x6e, 0x50, 0x6f, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x38, 0x0a, 0x03, 0x70, 0x6f, 0x63, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x63, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poc_proto_rawDescOnce sync.Once
	file_poc_proto_rawDescData = file_poc_proto_rawDesc
)

func file_poc_proto_rawDescGZIP() []byte {
	file_poc_proto_rawDescOnce.Do(func() {
		file_poc_proto_rawDescData = protoimpl.X.CompressGZIP(file_poc_proto_rawDescData)
	})
	return file_poc_proto_rawDescData
}

var file_poc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_poc_proto_goTypes = []interface{}{
	(*PocScanReq)(nil),    // 0: rpcServer.PocScanReq
	(*PocScanResult)(nil), // 1: rpcServer.PocScanResult
}
var file_poc_proto_depIdxs = []int32{
	0, // 0: rpcServer.RunPocScanService.poc:input_type -> rpcServer.PocScanReq
	1, // 1: rpcServer.RunPocScanService.poc:output_type -> rpcServer.PocScanResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poc_proto_init() }
func file_poc_proto_init() {
	if File_poc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PocScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PocScanResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poc_proto_goTypes,
		DependencyIndexes: file_poc_proto_depIdxs,
		MessageInfos:      file_poc_proto_msgTypes,
	}.Build()
	File_poc_proto = out.File
	file_poc_proto_rawDesc = nil
	file_poc_proto_goTypes = nil
	file_poc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RunPocScanServiceClient is the client API for RunPocScanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunPocScanServiceClient interface {
	Poc(ctx context.Context, in *PocScanReq, opts ...grpc.CallOption) (*PocScanResult, error)
}

type runPocScanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunPocScanServiceClient(cc grpc.ClientConnInterface) RunPocScanServiceClient {
	return &runPocScanServiceClient{cc}
}

func (c *runPocScanServiceClient) Poc(ctx context.Context, in *PocScanReq, opts ...grpc.CallOption) (*PocScanResult, error) {
	out := new(PocScanResult)
	err := c.cc.Invoke(ctx, "/rpcServer.RunPocScanService/poc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunPocScanServiceServer is the server API for RunPocScanService service.
type RunPocScanServiceServer interface {
	Poc(context.Context, *PocScanReq) (*PocScanResult, error)
}

// UnimplementedRunPocScanServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRunPocScanServiceServer struct {
}

func (*UnimplementedRunPocScanServiceServer) Poc(context.Context, *PocScanReq) (*PocScanResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poc not implemented")
}

func RegisterRunPocScanServiceServer(s *grpc.Server, srv RunPocScanServiceServer) {
	s.RegisterService(&_RunPocScanService_serviceDesc, srv)
}

func _RunPocScanService_Poc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PocScanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunPocScanServiceServer).Poc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.RunPocScanService/Poc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunPocScanServiceServer).Poc(ctx, req.(*PocScanReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RunPocScanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcServer.RunPocScanService",
	HandlerType: (*RunPocScanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "poc",
			Handler:    _RunPocScanService_Poc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poc.proto",
}
