// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunPocServiceClient is the client API for RunPocService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunPocServiceClient interface {
	Poc(ctx context.Context, in *PocReq, opts ...grpc.CallOption) (*PocResult, error)
}

type runPocServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunPocServiceClient(cc grpc.ClientConnInterface) RunPocServiceClient {
	return &runPocServiceClient{cc}
}

func (c *runPocServiceClient) Poc(ctx context.Context, in *PocReq, opts ...grpc.CallOption) (*PocResult, error) {
	out := new(PocResult)
	err := c.cc.Invoke(ctx, "/pb.RunPocService/poc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunPocServiceServer is the server API for RunPocService service.
// All implementations must embed UnimplementedRunPocServiceServer
// for forward compatibility
type RunPocServiceServer interface {
	Poc(context.Context, *PocReq) (*PocResult, error)
	mustEmbedUnimplementedRunPocServiceServer()
}

// UnimplementedRunPocServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRunPocServiceServer struct {
}

func (UnimplementedRunPocServiceServer) Poc(context.Context, *PocReq) (*PocResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poc not implemented")
}
func (UnimplementedRunPocServiceServer) mustEmbedUnimplementedRunPocServiceServer() {}

// UnsafeRunPocServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunPocServiceServer will
// result in compilation errors.
type UnsafeRunPocServiceServer interface {
	mustEmbedUnimplementedRunPocServiceServer()
}

func RegisterRunPocServiceServer(s grpc.ServiceRegistrar, srv RunPocServiceServer) {
	s.RegisterService(&RunPocService_ServiceDesc, srv)
}

func _RunPocService_Poc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunPocServiceServer).Poc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RunPocService/poc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunPocServiceServer).Poc(ctx, req.(*PocReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RunPocService_ServiceDesc is the grpc.ServiceDesc for RunPocService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunPocService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RunPocService",
	HandlerType: (*RunPocServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "poc",
			Handler:    _RunPocService_Poc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
